# Site
name: "Orson De Witt"
title: "Orson De Witt"
description: "Data analyst's storytelling endeavors. BirdMApp, Egypt: Shattered Order, Orca Hunting School and more."
logo: 'assets/images/logo.png'
logo-lightblue: 'assets/images/logo-lightblue.png'
logo-small: 'assets/images/logo-small.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
include: ["_pages"]
permalink: /posts/:title/
russian: 'https://ru.orsondewitt.com/'
english: 'https://orsondewitt.com'
email: 'author@orsondewitt.com'

# Links
books: '/books'
birdmapp: '/birdmapp'
games: 'https://orsondewitt.com/egypt' #'https://egypt.orcinus.games'

# Egypt
discord: 'https://discord.gg/Nmx4KDKuhJ'
steam_creator_page: 'https://store.steampowered.com/developer/orcinusgames/'
youtube: 'https://www.youtube.com/channel/UCdod8Lkks-QqSjm0epIHv-A'
subreddit: 'OrcinusGames'

# Authors
authors:
  Orson:
    name: Orson
    display_name: Orson
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: author@orsondewitt.com
    twitter: https://twitter.com/OrsonDeWitt
    description: "Description"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [CHANGELOG.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
